select
    ad_id,
    ad_name,
    campaign_id,
    campaign_name,
    objective,
    date(date_start) as spend_date,
    sum(spend) as daily_spend,
    sum(clicks) as daily_clicks,
    sum(impressions) as daily_impressions,
    avg(cpc) as avg_cpc,
    avg(cpm) as avg_cpm,
    avg(ctr) as avg_ctr,
    spend_cap,
    daily_budget,
    lifetime_budget,
    effective_status,
    buying_type
from {{ ref("canonical_meta_ads_campaigns") }}
group by
    ad_id,
    ad_name,
    campaign_id,
    campaign_name,
    objective,
    spend_date,
    spend_cap,
    daily_budget,
    lifetime_budget,
    effective_status,
    buying_type
