name: 'high_camp_flasks'
version: '1.3.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  
vars:
  facebook_ads_schema: meta_ads_airbyte
  google_ads_schema: google_ads_airbyte
  airbyte_google_ads.ad_group_ad_report: "{{ source('airbyte_google_ads', 'ad_group_ad_report') }}"
  airbyte_google_ads.ad_groups: "{{ source('airbyte_google_ads', 'ad_groups') }}"
  airbyte_google_ads.campaigns: "{{ source('airbyte_google_ads', 'campaigns') }}"
  airbyte_google_ads.click_view: "{{ source('airbyte_google_ads', 'click_view') }}"
  airbyte_google_ads.keyword_report: "{{ source('airbyte_google_ads', 'keyword_report') }}"