select
    sc.customer_id,
    sc.email,
    sc.first_name,
    sc.last_name,
    sc.phone,
    cmra.billing_address_1,
    cmra.billing_address_2,
    cmra.billing_city,
    cmra.billing_state,
    cmra.billing_state_code,
    cmra.billing_zip,
    cmra.billing_country,
    cmra.billing_country_code,
    sc.account_state,
    sc.customer_tags,
    sc.avg_order_value,
    sc.avg_quantity_per_order,
    sc.avg_discount_per_order,
    sc.avg_shipping_per_order,
    sc.avg_tax_per_order,
    sc.lifetime_abandoned_checkouts,
    sc.lifetime_total_spent,
    sc.lifetime_count_orders,
    sc.lifetime_total_refunded,
    sc.lifetime_total_net,
    sc.lifetime_total_discount,
    sc.lifetime_total_shipping,
    sc.lifetime_total_tax,
    cct.first_order_referring_site,
    sc.first_order_timestamp,
    cct.days_since_first_order,
    cct.most_recent_order_referring_site,
    sc.most_recent_order_timestamp,
    cct.days_since_most_recent_order,
    sc.created_timestamp as shopify_customer_created_at,
    sc.updated_timestamp as shopify_customer_updated_at,
from {{ ref("shopify__customers") }} sc
left join {{ ref("stg_customer_most_recent_address")}} cmra on sc.customer_id = cmra.customer_id
left join {{ ref("stg_customer_calculated_traits") }} cct on sc.customer_id = cct.customer_id
left join {{ ref("stg_customer_tag_counts") }} ctc on sc.customer_id = ctc.customer_id
