select
    so.order_id,
    so.order_number,
    so.customer_id,
    so.email,
    so.referring_site,
    so.landing_site_base_url,
    so.billing_address_first_name as billing_first_name,
    so.billing_address_last_name as billing_last_name,
    so.billing_address_phone as billing_phone,
    so.billing_address_company as billing_company,
    so.billing_address_address_1 as billing_address_1,
    so.billing_address_address_2 as billing_address_2,
    so.billing_address_city as billing_address_city,
    so.billing_address_province as billing_state,
    so.billing_address_province_code as billing_state_code,
    so.billing_address_zip as billing_zip,
    so.billing_address_country as billing_country,
    so.billing_address_country_code as billing_country_code,
    so.shipping_address_first_name as shipping_first_name,
    so.shipping_address_last_name as shipping_last_name,
    so.shipping_address_phone as shipping_phone,
    so.shipping_address_company as shipping_company,
    so.shipping_address_address_1 as shipping_address_1,
    so.shipping_address_address_2 as shipping_address_2,
    so.shipping_address_city as shipping_address_city,
    so.shipping_address_province as shipping_state,
    so.shipping_address_province_code as shipping_state_code,
    so.shipping_address_zip as shipping_zip,
    so.shipping_address_country as shipping_country,
    so.shipping_address_country_code as shipping_country_code,
    so.subtotal_price,
    so.line_item_count,
    so.total_line_items_price,
    so.total_price,
    so.total_discounts,
    so.total_tax,
    so.total_weight,
    so.refund_subtotal,
    so.order_adjusted_total,
    so.refund_total_tax,
    so.percentage_calc_discount_amount,
    so.fixed_amount_discount_amount,
    so.shipping_discount_amount,
    so.count_discount_codes_applied,
    so.source_name,
    so.new_vs_repeat,
    so.customer_order_seq_number,
    so.order_tags,
    so.financial_status,
    so.fulfillment_status,
    so.cancel_reason,
    so.created_timestamp,
    so.processed_timestamp,
    so.updated_timestamp,
    so.cancelled_timestamp,
    ({{ get_sku_array("so.order_id") }}) as current_order_skus,
    ({{ get_sku_array("os.first_order_id") }}) as first_order_skus,
    ({{ get_variant_sku_array("so.order_id") }}) as current_order_variant_ids,
    ({{ get_variant_sku_array("os.first_order_id") }}) as first_order_variant_ids,
    ({{ get_marketing_source("so.referring_site") }}) as current_order_marketing_source,
    ({{ get_marketing_medium("so.referring_site") }}) as current_order_marketing_medium,
    -- First order and sequencing data
    os.first_order_id as customers_first_order_id,
    os.first_order_date as customers_first_order_date,
    os.first_order_marketing_source,
    os.first_order_marketing_medium,
    os.days_between_orders as days_between_customers_first_and_current_order,
    os.months_between_orders_rounded_down
    as months_rounded_down_between_customers_first_and_current_order

from {{ ref("shopify__orders") }} so
left join {{ ref("stg_order_sequencing") }} os on so.order_id = os.order_id
