with orders as (
    select
        order_id,
        order_number,
        customer_id,
        email,
        created_at_timestamp,
        updated_at,
        cancelled_at,
        source_name,
        total_line_items_price,
        subtotal_price,
        total_discounts,
        total_price,
        financial_status,
        currency,
        referring_site,
        landing_site_base_url,
        fulfillment_status,
        cancel_reason,
        billing_address_1 as billing_address_address_1,
        billing_address_2 as billing_address_address_2,
        billing_city as billing_address_city,
        billing_company as billing_address_company,
        billing_country as billing_address_country,
        billing_country_code as billing_address_country_code,
        billing_first_name as billing_address_first_name,
        billing_last_name as billing_address_last_name,
        billing_latitude as billing_address_latitude,
        billing_longitude as billing_address_longitude,
        billing_name as billing_address_name,
        billing_phone as billing_address_phone,
        billing_province as billing_address_province,
        billing_province_code as billing_address_province_code,
        billing_zip as billing_address_zip
    from {{ ref('stg_shopify_orders_tmp') }}
),

final_orders as (
    select
        orders.order_id,
        orders.order_number,
        orders.customer_id,
        orders.email,
        orders.created_at_timestamp,
        orders.updated_at as updated_timestamp,
        orders.cancelled_at as cancelled_timestamp,
        orders.source_name,
        orders.total_line_items_price,
        orders.subtotal_price,
        orders.total_discounts,
        orders.total_price,
        orders.financial_status,
        orders.currency,
        orders.referring_site,
        orders.landing_site_base_url,
        orders.fulfillment_status,
        orders.cancel_reason,
        orders.billing_address_address_1,
        orders.billing_address_address_2,
        orders.billing_address_city,
        orders.billing_address_company,
        orders.billing_address_country,
        orders.billing_address_country_code,
        orders.billing_address_first_name,
        orders.billing_address_last_name,
        orders.billing_address_latitude,
        orders.billing_address_longitude,
        orders.billing_address_name,
        orders.billing_address_phone,
        orders.billing_address_province,
        orders.billing_address_province_code,
        orders.billing_address_zip
    from orders
)

select * from final_orders
